/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as ApiQueueRouteImport } from './routes/api/queue'
import { Route as ApiQueuePendingRouteImport } from './routes/api/queue.pending'
import { Route as ApiQueueIdRouteImport } from './routes/api/queue.$id'
import { Route as ApiAdminServeRouteImport } from './routes/api/admin/serve'
import { Route as ApiAdminReportRouteImport } from './routes/api/admin/report'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueRoute = ApiQueueRouteImport.update({
  id: '/api/queue',
  path: '/api/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueuePendingRoute = ApiQueuePendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => ApiQueueRoute,
} as any)
const ApiQueueIdRoute = ApiQueueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiQueueRoute,
} as any)
const ApiAdminServeRoute = ApiAdminServeRouteImport.update({
  id: '/api/admin/serve',
  path: '/api/admin/serve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReportRoute = ApiAdminReportRouteImport.update({
  id: '/api/admin/report',
  path: '/api/admin/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/track/$id': typeof TrackIdRoute
  '/api/admin/report': typeof ApiAdminReportRoute
  '/api/admin/serve': typeof ApiAdminServeRoute
  '/api/queue/$id': typeof ApiQueueIdRoute
  '/api/queue/pending': typeof ApiQueuePendingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/track/$id': typeof TrackIdRoute
  '/api/admin/report': typeof ApiAdminReportRoute
  '/api/admin/serve': typeof ApiAdminServeRoute
  '/api/queue/$id': typeof ApiQueueIdRoute
  '/api/queue/pending': typeof ApiQueuePendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/queue': typeof ApiQueueRouteWithChildren
  '/track/$id': typeof TrackIdRoute
  '/api/admin/report': typeof ApiAdminReportRoute
  '/api/admin/serve': typeof ApiAdminServeRoute
  '/api/queue/$id': typeof ApiQueueIdRoute
  '/api/queue/pending': typeof ApiQueuePendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/api/queue'
    | '/track/$id'
    | '/api/admin/report'
    | '/api/admin/serve'
    | '/api/queue/$id'
    | '/api/queue/pending'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/api/queue'
    | '/track/$id'
    | '/api/admin/report'
    | '/api/admin/serve'
    | '/api/queue/$id'
    | '/api/queue/pending'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/api/queue'
    | '/track/$id'
    | '/api/admin/report'
    | '/api/admin/serve'
    | '/api/queue/$id'
    | '/api/queue/pending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ApiQueueRoute: typeof ApiQueueRouteWithChildren
  TrackIdRoute: typeof TrackIdRoute
  ApiAdminReportRoute: typeof ApiAdminReportRoute
  ApiAdminServeRoute: typeof ApiAdminServeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue': {
      id: '/api/queue'
      path: '/api/queue'
      fullPath: '/api/queue'
      preLoaderRoute: typeof ApiQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue/pending': {
      id: '/api/queue/pending'
      path: '/pending'
      fullPath: '/api/queue/pending'
      preLoaderRoute: typeof ApiQueuePendingRouteImport
      parentRoute: typeof ApiQueueRoute
    }
    '/api/queue/$id': {
      id: '/api/queue/$id'
      path: '/$id'
      fullPath: '/api/queue/$id'
      preLoaderRoute: typeof ApiQueueIdRouteImport
      parentRoute: typeof ApiQueueRoute
    }
    '/api/admin/serve': {
      id: '/api/admin/serve'
      path: '/api/admin/serve'
      fullPath: '/api/admin/serve'
      preLoaderRoute: typeof ApiAdminServeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/report': {
      id: '/api/admin/report'
      path: '/api/admin/report'
      fullPath: '/api/admin/report'
      preLoaderRoute: typeof ApiAdminReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiQueueRouteChildren {
  ApiQueueIdRoute: typeof ApiQueueIdRoute
  ApiQueuePendingRoute: typeof ApiQueuePendingRoute
}

const ApiQueueRouteChildren: ApiQueueRouteChildren = {
  ApiQueueIdRoute: ApiQueueIdRoute,
  ApiQueuePendingRoute: ApiQueuePendingRoute,
}

const ApiQueueRouteWithChildren = ApiQueueRoute._addFileChildren(
  ApiQueueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ApiQueueRoute: ApiQueueRouteWithChildren,
  TrackIdRoute: TrackIdRoute,
  ApiAdminReportRoute: ApiAdminReportRoute,
  ApiAdminServeRoute: ApiAdminServeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
